require('./appform-mobile-field-location.tpl.html.js');
require('./appform-mobile-field.tpl.html.js');
require('./appform-mobile-submission-view.tpl.html.js');
require('./appform-mobile.tpl.html.js');
require('./appform-portal-field-location.tpl.html.js');
require('./appform-portal-field-number.tpl.html.js');
require('./appform-portal-field.tpl.html.js');
require('./appform-portal-view.tpl.html.js');
require('./appform-portal.tpl.html.js');
